### PR TITLE
Update to Angular 14

### PR DESCRIPTION
**Pull request by AbuHani**
Support for Angular 14!

### CODE REVIEW

**Comment by sandangel** [comment]
hi, can you share the command to upgrade? is that just nx update?

**Comment by AbuHani** [comment]
Hi @sandangel , i did both commands 

```
ng update
npx nx migrate latest
```
but i see npx nx it's enough since nx migrate is a much improved version of ng update

**Comment by AbuHani** [comment]
@sandangel  let me know if there is issue with this PR, i did the build, test commands and all working fine with me.

**Comment by sandangel** [comment]
yeah, since I already use `nx`, we don't need to run `ng update`. Could you help me confirm that the result from running `nx update` is the same with result in this PR?

**Comment by AbuHani** [comment]
Hey @sandangel i just updated the PR and fixed the issues of the migration ```nx migrate latest```  command. 

check it out and update the NPM package please. 

I need this ASAP

**Comment by sandangel** [comment]
closing in favor of #106

**Comment by sandangel** [comment]
thanks @AbuHani , thanks so much for you contribution

**Pull request closed without merging**
